version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  app:
    build:
      context: .

    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: better_notes
    
    ports:
      - 8000:8000


volumes:
  mongo:
