name: Lint & Test

on:
  - push

jobs:
  install-dependencies:
    name: Install dependencies & cache
    runs-on: ubuntu-latest
    steps:
      - name: Get python
        uses: actions/setup-python@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          $HOME/.poetry/bin/poetry config virtualenvs.in-project true
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Set up cache
        uses: actions/cache@v1
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Get python
        uses: actions/setup-python@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          $HOME/.poetry/bin/poetry config virtualenvs.in-project true
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Set up cache
        uses: actions/cache@v1
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Run linters
        run: make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Get python
        uses: actions/setup-python@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0

      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          $HOME/.poetry/bin/poetry config virtualenvs.in-project true
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Set up cache
        uses: actions/cache@v1
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Run tests
        run: make test
